version: '3.9'
services:
  db:
    container_name: learning-phoenix-framework-users-api-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '54321:5432'
